---
- name: Copy sshClients pubkeys to target authorized keys
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "./.ssh/*.pub"
#  loop: "{{ groups['sshClients'] }}"
