- hosts: dockerHosts
  tasks:
    - name: Ensure curl is installed
      package:
        name: curl
        state: present
    - name: Check if falco package is installed
      package_facts:
        manager: auto
    # - name: Check if falco-bpf service would have to be started
    #   systemd:
    #     name: falco-bpf
    #     state: started
    #     enabled: true
    #   check_mode: true
    #   register: falco_bpf_status
    #   when: "'falco' in ansible_facts.packages"
    - name: Install and run Falco
      block:
        - name: Install Falco components and dependencies
          shell:  curl https://falco.org/script/install | bash
        - name: Ensure bpf probes are available
          shell: falco-driver-loader bpf
      #   - name: Restart falco-bpf service
      #     systemd:
      #       name: falco-bpf
      #       state: restarted
      #       enabled: true
      # when: "falco_bpf_status.changed or 'falco' not in ansible_facts.packages"
      when: "'falco' not in ansible_facts.packages"
