- hosts: dockerHosts
  tasks:
    - name: Setup unattended upgrades
      package:
        name: unattended-upgrades
        state: present

- name: Isolate docker where required
  import_playbook: isolate-docker.yml

- name: Initialize docker swarm cluster
  import_playbook: init-swarm.yml

# - name: Push sshnfs configuration on all nodes
#   vars:
#     stacks: "{{ manual_stacks }}"
#   import_playbook: push-sshnfs.yml

# - name: Deploy IPS solutions in cluster
#   import_playbook: push-ips.yml

