# Turn this into a loop for scaling, and do the same for push-compose, using ansible dictionaries if necessary

- name: Destroy all compose stacks
  hosts: all
  # hosts must be all for the conditional to pick the correct ones
  tasks:
    - name: Push {{ item.stack_name }} compose stack (project {{ item.project_name }})
      include_role:
        name: 9xeb.push-compose
      when: "item.target in group_names"
      vars:
        # remote directory name
        project_name: "{{ item.project_name }}"
        # location of the compose override in ../docker/
        stack_name: "{{ item.stack_name }}"
        status: "{{ item.status }}"
        remove_volumes: true
      with_items:
        - { project_name: purpleids, stack_name: network, target: 'networkHosts', status: absent }
        - { project_name: purpleids, stack_name: analysis, target: 'analysisHosts', status: absent }
        - { project_name: purpleids, stack_name: dvwa, target: 'analysisHosts', status: absent }


- name: Destroy involved volumes in docker hosts
  hosts: dockerHosts
  vars_files:
    - vars/main.yml
  vars:
    project_name: purpleids
  tasks:
    - name: Destroy volume
      docker_volume:
        name: "{{ project_name ~ '_' ~ item }}"
        state: absent
      with_items: "{{ docker_volumes }}"

# TODO: delete 
