- name: Push crowdsec full setup
  # vars:
  #   stacks: "{{ swarm_infra_stacks }}"
  import_playbook: push-crowdsec.yml

- name: Push falco full setup
  # vars:
  #   stacks: "{{ swarm_infra_stacks }}"
  import_playbook: push-falco.yml