- name: Ensure falco modules are present
  import_playbook: ensure-falco-bpf.yml

- name: Run falco swarm stack
  hosts: swarmManagers[0]
  # hosts must be all so the conditional can pick the correct ones
  vars_files:
    - vars/main.yml
  vars:
    stacks: "{{ swarm_infra_stacks }}"
  tasks:
    - name: Push compose stack
      include_role:
        name: 9xeb.push-compose
      vars:
        stack_conf: "{{ item.conf + ['docker-compose.volumes.' ~ item.name ~ '.yml']}}"
        stack_dir: "{{ item.dir }}"
        #stack_env: "{{ item.env }}"
        stack_status: "{{ item.status }}"
        stack_name: "{{ item.name }}"
        swarm: true
      with_items: "{{ stacks }}"
      when: "item.name == 'falco'"