---
- name: Ensure main directory exists
  file:
    path: docker/{{ project_name }}
    state: directory
#- name: Push main compose file
#  copy:
#    src: docker-compose-ansible.yml
#    dest: docker/{{ project_name }}/docker-compose-ansible.yml
#  register: main_compose
- name: Push compose files
  copy:
    src: "{{ item }}"
    dest: docker/{{ project_name }}/{{ item }}
  with_items: "{{ stack_conf }}"
#   notify: stop stack and remove volumes
- name: Push targeted compose override directory
  copy:
#    src: "{{ stack_name }}"
#    src: "{{ item }}"
#    dest: docker/{{ project_name }}/{{ stack_name }}
    src: "{{ stack_dir ~ '/' }}"
    dest: docker/{{ project_name }}/{{ stack_dir }}/
#  loop: "{{ stack_list }}"
#- name: stop stack and remove volumes
#  command:
#    cmd: docker-compose -f docker-compose.yml -f {{ stack_name }}/docker-compose.yml --env-file {{ stack_name }}/.env down -v
#    chdir: docker/{{ project_name }}
#  become: true
#  when: main_compose.changed
#  ignore_errors: true
