# Required directories for volumes mounts
# zeek-logs
# zeek-spool
# suricata-logs
---


- name: Ensure main directory exists
  become: false
  file:
    path: docker/{{ project_name }}
    state: directory
- name: Push main compose file
  become: false
  copy:
    src: docker-compose-ansible.yml
    dest: docker/{{ project_name }}/docker-compose-ansible.yml
- name: Run compose file containing volumes definitions
  become: true
  command: docker-compose -f docker/{{ project_name }}/docker-compose-ansible.yml up -d --build
#  docker_compose:
#    project_src: docker/
#    files:
#      - docker-compose-ansible.yml
#    build: yes
#    pull: yes
#    state: present
#    debug: yes
#- name: Run compose file containing volumes definitions
#  docker_compose:
#    project_src: docker/{{ project_name }}
#    files:
#      - docker-compose.yml
#    build: yes
#    pull: yes
#    state: present
