# Required directories for volumes mounts
# zeek-logs
# zeek-spool
# suricata-logs
---


- name: Ensure main directory exists
  file:
    path: docker/{{ project_name }}
    state: directory
- name: Push main compose file
  copy:
    src: docker-compose.yml
    dest: docker/{{ project_name }}/docker-compose.yml
- name: Run compose file containing volumes definitions
  command: docker-compose -f docker/{{ project_name}}/docker-compose.yml up -d --build

#- name: Run compose file containing volumes definitions
#  docker_compose:
#    project_src: docker/{{ project_name }}
#    files:
#      - docker-compose.yml
#    build: yes
#    pull: yes
#    state: present
