- name: Ensure borgbackup is installed on backup host
  package:
   name: borgbackup
    state: latest
      # check if AllowGroups line is present
- command: grep "^AllowGroups " /etc/ssh/sshd_config
  ignore_errors: yes
  register: allowed_groups_list
    # check if AllowUsers line contains desired user
- command: grep '^AllowGroups .*ssh.*' /etc/ssh/sshd_config
  ignore_errors: yes
  register: allowed_groups_list_with_ssh_group
- name: Append ssh to SSH allowed groups
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowGroups .+"
    line: "{{ allowed_groups_list.stdout }} ssh"
  when:
    - allowed_groups_list.rc == 0
    - allowed_groups_list_with_ssh_group.rc != 0
- name: Add AllowGroups line containing group ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: AllowGroups ssh
  when:
    - allowed_groups_list.rc != 0
