- name: Push targeted compose override directory
  copy:
#    src: "{{ stack_name }}"
#    src: "{{ item }}"
#    dest: docker/{{ project_name }}/{{ stack_name }}
    src: "{{ build_dir ~ '/' }}"
    dest: docker/{{ project_name }}/{{ build_dir }}/

- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ registry_name }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    reauthorize: yes
    

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: docker/{{ project_name }}/{{ build_dir }}
    name: "{{ registry_name ~ '/' ~ build_name }}"
    tag: "{{ build_tag }}"
    push: true
    source: build
    force_source: true

# - name: Log out of private registry
#   docker_login:
#     registry: "{{ registry_name }}"
#     username: "{{ registry_username }}"
#     password: "{{ registry_password }}"
#     state: absent