---

# wants crowdsec_lapi_url and crowdsec_bouncer_api_key vars
- name: Ensure crowdsec-iptables-bouncer is installed
  block:
    - name: Import crowdsec mirrors
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
    - name: Ensure crowdsec-firewall-bouncer-iptables is installed
      package:
        name: crowdsec-firewall-bouncer-iptables
        state: present
    - name: Update bouncer's configuration to point to proper LAPI
      template:
        src: crowdsec-firewall-bouncer.yaml.j2
        dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
    - name: Restart bouncer service
      systemd:
        name: crowdsec-firewall-bouncer-iptables
        state: restarted
        enabled: true        
  become: true
