---

- name: Check if falco package is installed
  package_facts:
    manager: auto
# wants crowdsec_lapi_url and crowdsec_bouncer_api_key vars
- name: Ensure crowdsec-iptables-bouncer is installed
  block:
    - name: Import crowdsec mirrors
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
    - name: Ensure crowdsec-firewall-bouncer-iptables is installed
      package:
        name: crowdsec-firewall-bouncer-iptables
        state: present
  when: "'crowdsec-firewall-bouncer-iptables' not in ansible_facts.packages"
  become: true

- name: Update bouncer's configuration to point to proper LAPI
  template:
    src: crowdsec-firewall-bouncer.yaml.j2
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
  become: true

- name: Stop bouncer service
  systemd:
    name: crowdsec-firewall-bouncer
    state: stopped
    enabled: true
  become: true
- name: Start bouncer service
  systemd:
    name: crowdsec-firewall-bouncer
    state: started
    enabled: true
  become: true