---
- name: Ensure docker and ethtool are installed
  package:
    name: 
      - docker.io
      - ethtool
    state: present

- name: Copy initialization helper
  copy:
    src: netns-veth@.service
    dest: /etc/systemd/system/netns-veth@.service
- name: Template access helper
  template:
    src: netns-veth-access@.service.j2
    dest: /etc/systemd/system/netns-veth-access@.service
- file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Copy service drop-in for docker
  copy:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf

- systemd:
    daemon_reload: true
- shell: systemctl stop docker && systemctl start docker
# - systemd:
#     name: docker
#     state: stopped
# - systemd:
#     name: docker
#     state: started

- name: Accept output forward to network namespace ips
  ansible.builtin.iptables:
    action: insert
    chain: FORWARD
    source: "{{ veth_subnet }}"
    in_interface: "{{ veth_name }}"
    jump: ACCEPT

- name: Accept input forward to network namespace ips
  ansible.builtin.iptables:
    action: insert
    chain: FORWARD
    destination: "{{ veth_subnet }}"
    in_interface: wg0
    jump: ACCEPT

- name: DNAT unit services coming from wireguard VPN
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: wg0
    protocol: "{{ item.proto }}"
    match: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    jump: DNAT
    to_destination: "{{ veth_ip }}"
    comment: Redirect {{ item.port }} traffic to "{{ veth_ip }}"
  become: yes
  loop: "{{ port_mappings }}"
  when: item.enabled