---
- name: Ensure docker is installed
  package:
    name: docker.io
    state: present
- name: Copy initialization helper
  copy:
    src: netns-veth@.service
    dest: /etc/systemd/system/netns-veth@.service
- name: Template access helper
  template:
    src: netns-veth-access@.service.j2
    dest: /etc/systemd/system/netns-veth-access@.service
- file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Copy service drop-in for docker
  copy:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf
- systemd:
    daemon_reload: true
- systemd:
    name: docker
    state: restarted

